# Generated by Django 5.2 on 2025-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=100)),
                ("marca", models.CharField(max_length=50)),
                ("lote", models.CharField(max_length=20)),
                ("fecha_vencimiento", models.DateField()),
                ("precio_lista", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_disponible", models.PositiveIntegerField()),
                ("unidad_medida", models.CharField(max_length=20)),
                ("requiere_receta", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
